package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/iamEtornam/mergejury/internal/adapter"
	"github.com/iamEtornam/mergejury/internal/anthropic"
	"github.com/iamEtornam/mergejury/internal/config"
	"github.com/iamEtornam/mergejury/prompts"
)

// candidate is one reviewer mergejury knows how to drive, with the lens it
// gets when it is available. Order is priority order: the lens each kind is
// best at, assigned to whichever tools the machine actually has.
type candidate struct {
	kind string
	lens string
	// model is left empty where the tool's own default is the right choice.
	model string
}

var candidates = []candidate{
	{kind: "claude-code", lens: "security"},
	{kind: "cursor", lens: "correctness"},
	{kind: "antigravity", lens: "api-contract"},
	{kind: "modelapi", lens: "test-gap", model: "claude-sonnet-5"},
}

// detection is what a probe found for one candidate.
type detection struct {
	candidate
	available   bool
	detail      string
	remediation string
}

// plan turns probe results into a config plus the list of gaps worth telling
// the user about. Pure: no subprocesses, no filesystem, so it is testable.
func plan(base config.Config, dets []detection) (config.Config, []string) {
	cfg := base
	cfg.Adapters = nil
	var gaps []string

	for _, d := range dets {
		if !d.available {
			if d.remediation != "" {
				gaps = append(gaps, fmt.Sprintf("%s: %s", d.kind, d.remediation))
			}
			continue
		}
		cfg.Adapters = append(cfg.Adapters, config.Adapter{
			ID:      d.kind,
			Kind:    d.kind,
			Lens:    d.lens,
			Model:   d.model,
			Timeout: 5 * time.Minute,
		})
	}

	// A single reviewer is a valid setup, but the lens matters more than the
	// label: the broadest lens is the right one when nothing else is running.
	if len(cfg.Adapters) == 1 && cfg.Adapters[0].Kind == "modelapi" {
		cfg.Adapters[0].Lens = "correctness"
	}
	return cfg, gaps
}

// renderConfig writes the starter config by hand rather than marshalling, so
// the file a user opens has comments and readable durations.
func renderConfig(cfg config.Config) string {
	var b strings.Builder
	b.WriteString("# mergejury configuration.\n")
	b.WriteString("# Generated by `mergejury init` from the tools found on this machine.\n")
	b.WriteString("# Credentials are never stored here; they come from the environment.\n\n")

	b.WriteString("adapters:\n")
	for _, a := range cfg.Adapters {
		fmt.Fprintf(&b, "  - id: %s\n", a.ID)
		fmt.Fprintf(&b, "    kind: %s\n", a.Kind)
		fmt.Fprintf(&b, "    lens: %s\n", a.Lens)
		if a.Model != "" {
			fmt.Fprintf(&b, "    model: %s\n", a.Model)
		}
		fmt.Fprintf(&b, "    timeout: %s\n", a.Timeout)
	}

	fmt.Fprintf(&b, `
gates:
  max_changed_lines: %d
  max_changed_files: %d

adjudication:
  cluster_window_lines: %d
  challenger:
    enabled: %t
    min_severity: %s
    model: %s
  judge:
    model: %s

posting:
  max_inline_comments: %d
  min_severity: %s
  dry_run: false

verdict:
  # Ship with verdicts off until you have watched a few dry runs and
  # verified the posting identity against a scratch repository.
  enabled: false
  request_changes_at: %s
  approve_on_clean: %t
  approve_forks: false
`,
		cfg.Gates.MaxChangedLines, cfg.Gates.MaxChangedFiles,
		cfg.Adjudication.ClusterWindowLines,
		cfg.Adjudication.Challenger.Enabled, cfg.Adjudication.Challenger.MinSeverity, cfg.Adjudication.Challenger.Model,
		cfg.Adjudication.Judge.Model,
		cfg.Posting.MaxInlineComments, cfg.Posting.MinSeverity,
		cfg.Verdict.RequestChangesAt, cfg.Verdict.ApproveOnClean,
	)
	return b.String()
}

const (
	tick  = "ok  "
	cross = "--  "
)

func newInitCmd() *cobra.Command {
	var (
		assumeYes bool
		force     bool
		printOnly bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "set up mergejury: probe the tools you have, write a matching config",
		Long: "Probes every reviewer mergejury knows how to drive, reports what is\n" +
			"missing and how to fix it, and writes a mergejury.yaml wired to the\n" +
			"tools this machine actually has. Credentials are never written to the\n" +
			"config; they are read from the environment at run time.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			out := cmd.OutOrStdout()
			wd, _ := os.Getwd()
			base, err := config.Load(wd)
			if err != nil {
				return withCode(err, exitConfigAuth)
			}
			ps := prompts.New(base.PromptsDir)
			client := anthropic.NewFromEnv()

			fmt.Fprintln(out, "Looking for reviewers on this machine.")
			fmt.Fprintln(out)

			dets := probeCandidates(cmd.Context(), ps, client)
			for _, d := range dets {
				mark := cross
				if d.available {
					mark = tick
				}
				fmt.Fprintf(out, "  %s%-14s %-14s %s\n", mark, d.kind, d.lens, d.detail)
			}

			cfg, gaps := plan(base, dets)
			fmt.Fprintln(out)
			if len(cfg.Adapters) == 0 {
				fmt.Fprintln(out, "No reviewer is usable yet, so there is nothing to configure.")
				fmt.Fprintln(out)
				printGaps(out, gaps)
				fmt.Fprintln(out, "\nThe cheapest way to start is the API reviewer: set ANTHROPIC_API_KEY and run `mergejury init` again.")
				return withCode(fmt.Errorf("no usable reviewer"), exitConfigAuth)
			}

			fmt.Fprintf(out, "Planned setup: %d reviewer(s), %s.\n",
				len(cfg.Adapters), strings.Join(lensList(cfg), ", "))
			if len(gaps) > 0 {
				fmt.Fprintln(out)
				printGaps(out, gaps)
			}

			body := renderConfig(cfg)
			if printOnly {
				fmt.Fprintln(out)
				fmt.Fprint(out, body)
				return nil
			}

			path := filepath.Join(wd, "mergejury.yaml")
			if _, err := os.Stat(path); err == nil && !force {
				fmt.Fprintf(out, "\n%s already exists; leaving it alone. Use --force to overwrite, or --print to see what would be written.\n", path)
				return nil
			}

			fmt.Fprintf(out, "\nWrite this to %s?", path)
			if !confirm(cmd.InOrStdin(), out, assumeYes, isTerminal(cmd.InOrStdin())) {
				fmt.Fprintln(out, "Nothing written. `mergejury init --print` shows the config without saving it.")
				return nil
			}
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				return err
			}
			fmt.Fprintf(out, "Wrote %s\n", path)

			fmt.Fprintln(out, "\nNext:")
			fmt.Fprintln(out, "  mergejury review --local     review your working tree; nothing is posted")
			fmt.Fprintln(out, "  mergejury serve              the operator console on localhost")
			fmt.Fprintln(out, "\nVerdicts are off in this config. Turn them on once you have watched a few")
			fmt.Fprintln(out, "dry runs and pointed the posting identity at a scratch repository.")
			return nil
		},
	}
	cmd.Flags().BoolVarP(&assumeYes, "yes", "y", false, "do not prompt; write the config")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing mergejury.yaml")
	cmd.Flags().BoolVar(&printOnly, "print", false, "print the config instead of writing it")
	return cmd
}

func probeCandidates(ctx context.Context, ps *prompts.Set, client *adapter.AnthropicClient) []detection {
	dets := make([]detection, 0, len(candidates))
	for _, c := range candidates {
		d := detection{candidate: c}
		rev, err := adapter.New(config.Adapter{ID: c.kind, Kind: c.kind, Lens: c.lens, Model: c.model}, ps, adapter.ExecRunner, client)
		if err != nil {
			d.detail = err.Error()
			dets = append(dets, d)
			continue
		}
		pr := rev.Probe(ctx)
		d.available = pr.OK
		d.detail = pr.Detail
		d.remediation = pr.Remediation
		dets = append(dets, d)
	}
	return dets
}

func lensList(cfg config.Config) []string {
	out := make([]string, 0, len(cfg.Adapters))
	for _, a := range cfg.Adapters {
		out = append(out, a.Lens)
	}
	return out
}

func printGaps(out io.Writer, gaps []string) {
	fmt.Fprintln(out, "Not available (each one is optional; mergejury degrades rather than fails):")
	for _, g := range gaps {
		fmt.Fprintf(out, "  - %s\n", g)
	}
}

// isTerminal reports whether r is an interactive terminal. Anything else (a
// pipe, a CI runner, a file) is not, and must never be prompted.
func isTerminal(r io.Reader) bool {
	f, ok := r.(*os.File)
	if !ok {
		return false
	}
	info, err := f.Stat()
	return err == nil && info.Mode()&os.ModeCharDevice != 0
}

// confirm asks a yes/no question. Whether prompting is possible is decided by
// the caller, so this never blocks on a pipe: the answer there is no unless
// --yes was passed.
func confirm(in io.Reader, out io.Writer, assumeYes, interactive bool) bool {
	if assumeYes {
		fmt.Fprintln(out, " yes")
		return true
	}
	if !interactive {
		fmt.Fprintln(out, " no (not a terminal; pass --yes to write)")
		return false
	}
	fmt.Fprint(out, " [y/N] ")
	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		fmt.Fprintln(out)
		return false
	}
	answer := strings.ToLower(strings.TrimSpace(scanner.Text()))
	return answer == "y" || answer == "yes"
}
